### ISSUE TITLE
[create-release.yml] Do not try to commit empty "raising version" commit

### ISSUE THREAD

**Issue by czthiele** [ZEISS-PiWeb/github-actions#8]
If all .csproj versions are already correct, the release workflow will fail since there nothing to commit.

**Comment by czthiele** [comment]
But Git Version only relies on commits and tags and will therefore not read from .csproj files (correct me if im wrong), so it won't influence the workflow. At least for users building the projects locally it is neccessary that the versions are up to date in the project files. 
Maybe we can somehow skip the commit if the command created no changes in the .csproj-file? Dont know if this is easily detectable though.

**Comment by georg-eckert-zeiss** [comment]
It won't read from then, but it will write the current version into them.

**Comment by georg-eckert-zeiss** [comment]
Right. Now I understand. The problem is still, that we need something to commit, or am I mistaken? Hold on. We can just merge into `main`. That should be fine.

The problem with contributors messing up version numbers stays. I would say it's fine for the workflow to fail. The contributor just has to remove his changes to the version number and run it again.

We could simply display an error message.

**Comment by czthiele** [comment]
After some discussion we decided to keep it as it is, contributors should simply not update the version. The workflow will do this.
